install: |
  sudo apt-get update -y
  sudo apt-get install make upstart gcc g++ make -y --no-install-recommends

setup: |
  echo 'SETUP'

test_suite:
  command: sh

  files:
    - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh

  env:
    - FOO=bar