install: |
  sudo apt-get update -y
  sudo apt-get install make upstart gcc g++ make -y --no-install-recommends

setup: |
  echo 'SETUP'

test_suite:
  command: echo

  files:
    - test/*_test.rb

  env:
    - FOO=bar